import type { PracticeData } from "./types.ts";

export const EXAMPLE_DATA: PracticeData = {
  surname: "Example",
  givenName: "Alex",
  nativeName: "示例人物",
  usedOtherNames: "no",
  sex: "OTHER",
  maritalStatus: "MARRIED",
  dateOfBirth: "1990-01-15",
  birthCity: "Sample City",
  birthState: "Example Province",
  birthCountry: "EXAMPLELAND",
  nationality: "EXAMPLELAND",
  hasOtherNationality: "no",
  nationalId: "DEMO-ID-2026",
  address1: "100 Example Avenue",
  address2: "Demo Apartment 2",
  homeCity: "Sample City",
  homeState: "Example Province",
  postalCode: "DEMO-0100",
  homeCountry: "EXAMPLELAND",
  mailingSame: "yes",
  primaryPhone: "+1 202-555-0100",
  secondaryPhone: "+1 202-555-0188",
  practiceEmail: "alex@example.com",
  passportType: "REGULAR",
  passportNumber: "DEMO123456",
  passportBookNumber: "DEMOBOOK01",
  passportAuthority: "Exampleland Practice Authority",
  passportIssueCity: "Sample City",
  passportIssueCountry: "EXAMPLELAND",
  passportIssueDate: "2025-01-15",
  passportExpiration: "2035-01-14",
  lostPassport: "no",
  practiceVisaCategory: "F1",
  tripPurpose: "EDUCATIONAL_PRACTICE",
  arrivalDate: "2027-05-10",
  stayLength: "10 DAYS",
  tripAddress: "100 Example Avenue, Sample City",
  tripPayer: "SELF",
  specificPlans: "yes",
  arrivalFlight: "DEMO101",
  arrivalCity: "Sample City",
  departureDate: "2027-05-20",
  departureCity: "Example City",
  hasCompanions: "yes",
  isGroupTravel: "no",
  companions: [
    { surname: "Sample", givenName: "Taylor", relationship: "FRIEND" }
  ],
  hasPreviousTravel: "yes",
  previousTravelDate: "2024-06-01",
  previousStayLength: "7 DAYS",
  hadPreviousVisa: "yes",
  previousVisaNumber: "DEMO-VISA-01",
  wasRefused: "no",
  usContactName: "Taylor Sample",
  usOrganization: "Sample Training Center",
  usRelationship: "FRIEND",
  usContactAddress: "100 Example Avenue, Sample City",
  usContactPhone: "+1 202-555-0142",
  usContactEmail: "contact@example.com",
  fatherSurname: "Example",
  fatherGivenName: "Morgan",
  fatherDob: "1960-02-12",
  motherSurname: "Sample",
  motherGivenName: "Jordan",
  motherDob: "1962-09-20",
  spouseName: "Casey Example",
  spouseDob: "1991-08-08",
  hasImmediateRelatives: "no",
  occupation: "EMPLOYED",
  employerName: "Example Learning Studio",
  practiceSchoolName: "Example Learning University",
  practiceSevisId: "DEMO-SEVIS-001",
  employerAddress: "300 Sample Street, Demo City",
  workStartDate: "2022-03-01",
  incomeNotApplicable: false,
  monthlyIncome: "5000",
  duties: "Designs fictional learning materials and delivers sample workshops.",
  hasPreviousEmployment: "yes",
  previousEmployment: [
    { name: "Demo Education Lab", role: "Practice Coordinator", start: "2018-01-01", end: "2022-02-28" }
  ],
  educationHistory: [
    { school: "Exampleland Learning Institute", subject: "Educational Practice", start: "2008-09-01", end: "2012-06-30" }
  ],
  languages: ["Example Language", "English"],
  countriesVisited: ["Exampleland", "Sample Islands"],
  belongsToOrganizations: "no",
  hasSpecialSkills: "no",
  hasMilitaryService: "no",
  securityHealth: "no",
  securityLegal: "no",
  securityImmigration: "no",
  securityMisrepresentation: "no",
  securitySafety: "no",
  securityOther: "no"
};
